---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: 12.16.42

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.3

suites:
  - name: default
    driver:
      network:
        - ["private_network", {ip: "33.33.33.11"}]
    run_list:
      - recipe[hms::default]
    attributes:
